# Generated by Django 5.0.6 on 2024-06-26 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='serviciosImg')),
                ('precio', models.IntegerField(default=999999)),
                ('fechaSolicitado', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='postsImg')),
                ('trabajo', models.CharField(choices=[('1', 'Servicio 1'), ('2', 'Servicio 2'), ('3', 'Servicio 3'), ('4', 'Servicio 4')], default='1', max_length=20)),
                ('estado', models.CharField(choices=[('R', 'Rechazado'), ('P', 'Pendiente'), ('A', 'Aprobado')], default='P', max_length=10)),
                ('razonRechazo', models.CharField(blank=True, max_length=256, null=True)),
                ('fecha', models.DateField()),
                ('idMecanico', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanicoActivo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
