# Generated by Django 5.0.6 on 2024-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='posts')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
