# Generated by Django 5.0.6 on 2024-06-23 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='serviciosImg')),
                ('fechaSolicitado', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='idMecanico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mecanicoActivo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(upload_to='postsImg'),
        ),
    ]
