# Generated by Django 5.0.6 on 2024-06-23 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicio_publicacion_idmecanico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='idMecanico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mecanicoActivo', to=settings.AUTH_USER_MODEL),
        ),
    ]
