# Generated by Django 5.0.6 on 2024-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_publicacion_razonrechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='trabajo',
            field=models.CharField(choices=[('Servicio 1', 'Servicio 1'), ('Servicio 2', 'Servicio 2'), ('Servicio 3', 'Servicio 3'), ('Servicio 4', 'Servicio 4')], default='1', max_length=20),
        ),
    ]
