# Generated by Django 5.0.6 on 2024-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_publicacion_estado_alter_publicacion_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='trabajo',
            field=models.CharField(choices=[('Servicio1', 'Servicio 1'), ('Servicio2', 'Servicio 2'), ('Servicio3', 'Servicio 3'), ('Servicio4', 'Servicio 4')], default='1', max_length=20),
        ),
    ]
