# Generated by Django 5.0.6 on 2024-06-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_publicacion_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('R', 'Rechazado'), ('P', 'Pendiente'), ('A', 'Aprobado')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='trabajo',
            field=models.CharField(choices=[('1', 'Servicio 1'), ('2', 'Servicio 2'), ('3', 'Servicio 3'), ('4', 'Servicio 4')], default='1', max_length=20),
        ),
    ]
