# Generated by Django 5.0.6 on 2024-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_publicacion_idmecanico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='trabajo',
            field=models.CharField(choices=[('1', 'Servicio 1'), ('2', 'Servicio 2'), ('3', 'Servicio 3'), ('4', 'Servicio 4')], default='1', max_length=20),
        ),
    ]
