# Generated by Django 5.0.6 on 2024-06-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_publicacion_estado_alter_publicacion_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='trabajo',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(blank=True, default=1, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(blank=True, default=1, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='razonRechazo',
            field=models.CharField(blank=True, default=1, max_length=256, null=True),
        ),
    ]
