# Generated by Django 5.0.6 on 2024-06-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_publicacion_trabajo_publicacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicioRealizado', to='core.servicio'),
        ),
    ]
