# Generated by Django 5.0.6 on 2024-06-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_publicacion_idmecanico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(upload_to="{% static 'img/postsImg' %}"),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaSolicitado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
